config/routes.rb
IsfitCore::Application.routes.draw do

 # match 'user/edit' => 'users#edit', :as => :edit_current_user

 # match 'signup' => 'users#new', :as => :signup

  resources :users do
    member do
      post 'generate_password'
    end
  end

  resources :roles
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resources :sessions
 # resources :organization do
 #   resources :festivals do
 #     resources :sections do
 #       resources :groups do
 #         resources :positions
 #       end
 #     end
 #     resources :groups do
 #       resources :positions
 #     end
 #   end
 #   resources :groups do
 #     resources :positions
 #   end
 # end

  resources :organization do
    resources :festivals
    resources :groups
  end
  resources :festivals do
    resources :sections
    resources :groups
  end
  resources :sections do
    resources :groups
  end
  resources :groups do
    resources :positions
  end
  resources :positions do
    resources :people
  end
  resources :people
  resources :isfit
  #match ':controller/:action' => '#index'
  root :to => "organization#show"
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :users
  has_and_belongs_to_many :groups
  belongs_to :group

  validates_presence_of :title_en, :title_no
  attr_reader :group_tokens, :user_tokens

  def group_tokens=(ids)
    self.group_ids = ids.split(",")
  end
  def user_tokens=(ids)
    self.user_ids = ids.split(",")
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  def show
    @position = Position.find(params[:id])  
  end

  def new
    @position = Position.new
    @group = Group.find_by_id(params[:group_id])
    @groups = []
    groups = Festival.find_by_year(session[:festival_year]).groups
    for group in groups
      @groups.push(group)
    end
    sections = Festival.find_by_year(session[:festival_year]).sections
    for section in sections
      for group in section.groups
        @groups.push(group)
      end
    end
  end

  def create
    @position = Position.new(params[:position])
    @position.admission_id = 1
    @group = Group.find_by_id(params[:group_id])
    @position.groups << @group
    if @position.save
      redirect_to @position, :notice => "Successfully created position."
    else
      render :action => 'new'
    end
  end

  def edit
    @position = Position.find_by_id(params[:id])
    @groups = Group.find(:all)
    @group = Group.find_by_id(params[:group_id])
  end

  def update
    @position = Position.find(params[:id])
    if @position.update_attributes(params[:position])
       redirect_to @position, :notice => "Successfully created position."
    else
      render :action => 'edit'
    end 
  end

end

app/views/positions/_form.html.erb
<%= form_for [@group, @position] do |f| %>
   <% if @position.errors.any? %>
    <div id="errorExplanation">  
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>  
      <ul>  
        <% @position.errors.full_messages.each do |msg| %>  
          <li><%= msg %></li>  
        <% end %>  
      </ul>  
    </div>                                    
  <% end %> 
  <%= f.label :title_en %>
  <%= f.text_field :title_en, :class => 'text' %>
  <%= f.label :title_no %>
  <%= f.text_field :title_no, :class => 'text' %>
  <%= f.label :holder %>
	<%= f.text_field :user_tokens, "data-pre" => @position.users.map(&:id_name).to_json %>
  <%= link_to t('users.actions.new'), new_user_path %>

  <p>Det kan være lurt å legge til litt margin på tidspunktene under. Tider er i UTC.</p>
  <%= f.label "Publish from" %>
  <%= f.text_field :publish_from %><small>YYYY-MM-DD HH:MM</small>
  <%= f.label "Publish to" %>
  <%= f.text_field :publish_to %><small>YYYY-MM-DD HH:MM</small>
  <%= f.label "English description" %>
  <%= f.text_area :description_en, :class => 'text_area' %>
  <%= f.label "Norwegian description" %>
  <%= f.text_area :description_no, :class => 'text_area' %>
  <%#= f.label :group_dn %>
  <%#= f.text_area(:group_dn, :class => 'text_area') %>
  <%#= f.label(:admission_id) %>
  <%#= f.text_field(:admission_id, :class => 'text') %> 
  <%#= f.label("Main group of position") %>
  <%#= f.select 'group_id', @groups.to_select_2 %> 
  <%= f.label :groups %>
	<%= f.text_field :group_tokens, "data-pre" => @position.groups.map(&:id_name).to_json %>
  <%= f.submit %>
<%end%>

app/views/positions/_list.html.erb
<table id="positionList">
  <tr>
    <th><%= t('positions.title') %></th>
    <th>group_dn</th>
    <th>admission_id</th>
  </tr>
  <% positions.each do |position| %>
  <tr class="<%= cycle(:odd, :even) %>">
    <td><%= link_to(position.title_en, position_path(position)) %></td>
    <td><%= position.group_dn %></td>
    <td><%= position.admission_id %></td>
  </tr>
  <% end %>
</table>

app/views/positions/edit.html.erb
<h2><%= t('positions.actions.edit') %></h2>
<%= render 'form' %>

app/views/positions/new.html.erb
<h2>New position</h2>
<%= render 'form' %>

app/views/positions/show.html.erb
<div id="toolbar">
  <%= link_to("Edit position", edit_position_path(@position), :class => :edit) %> 
</div>
<div id="items">
  <h2>Information</h2>
  <% if @position.groups.any? %>
    <h3>This position is part of the following groups</h3>
    <%= render :partial => 'groups/list', :locals => {:groups => @position.groups} %>
  <% else %>
    Empy position
  <% end %>
  <h3>Position information</h3>
  <p><b>English title:</b> <%= @position.title_en %><br>
    <b>Norwegian title:</b> <%= @position.title_no %><br>
    <b>Current holders:</b> <%#= link_to @position.person.name, person_path(@position.person) %>
      <ul>
        <% @position.users.each do |u| %>
          <li> <%= link_to u.name, user_path(u) %></li>
        <% end %>
      </ul>
  </p>

  <p><b>Publish from</b><br>
  <%= @position.publish_from %>
  </p>
  <p><b>Publish to</b><br>
  <%= @position.publish_to %>
  </p>
  <p><b>English description</b><br>
    <%= @position.description_en %>
  </p>
  <p><b>Norwegian description</b><br>
    <%= @position.description_no %>
</p>
</div>  