config/routes.rb
IsfitCore::Application.routes.draw do

 # match 'user/edit' => 'users#edit', :as => :edit_current_user

 # match 'signup' => 'users#new', :as => :signup

  resources :users do
    member do
      post 'generate_password'
    end
  end

  resources :roles
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resources :sessions
 # resources :organization do
 #   resources :festivals do
 #     resources :sections do
 #       resources :groups do
 #         resources :positions
 #       end
 #     end
 #     resources :groups do
 #       resources :positions
 #     end
 #   end
 #   resources :groups do
 #     resources :positions
 #   end
 # end

  resources :organization do
    resources :festivals
    resources :groups
  end
  resources :festivals do
    resources :sections
    resources :groups
  end
  resources :sections do
    resources :groups
  end
  resources :groups do
    resources :positions
  end
  resources :positions do
    resources :people
  end
  resources :people
  resources :isfit
  #match ':controller/:action' => '#index'
  root :to => "organization#show"
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :festival
  has_many :groups
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def show
    @section = Section.find_by_id(params[:id])
    set_where_am_i(@section)
  end

  def new
    @section = Section.new
    @section.festival = Festival.find_by_id(params[:festival_id])
  end

  def create
    @section = Section.new(params[:section])
    @section.festival = Festival.find_by_id(params[:festival_id])
    save_section
  end

  def edit
    @section = Section.find_by_id(params[:id])
    render(:action => 'new')
  end

  def update
    @section = Section.find_by_id(params[:id])
    @section.attributes = params[:section]
    save_section
  end

  def index
    redirect_to(festival_path(params[:festival_id]))
  end

  private

  def save_section
    if @section.save
      redirect_to(festival_section_path(@section.festival,@section))
    else
      render(:action => 'new')
    end
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for([@section.festival, @section]) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_en %><br />
    <%= f.text_field :name_en %>
  </div>
  <div class="field">
    <%= f.label :name_no %><br />
    <%= f.text_field :name_no %>
  </div>
  <div class="field">
    <%= f.hidden_field :festival_id %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :description_en %><br />
    <%= f.text_area :description_en %>
  </div>
  <div class="field">
    <%= f.label :description_no %><br />
    <%= f.text_area :description_no %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/_list.html.erb
<% sections.each do |section| %>
  <div class="<%= cycle(:odd, :even) %>">
    <%= link_to(section.name_en, festival_section_path(section.festival, section), :class => :section) %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render 'form' %>

<%= link_to 'Show', festival_section_path(@section.festival, @section) %> |
<%= link_to 'Back', festival_sections_path %>

app/views/sections/index.html.erb
<h1>Listing sections</h1>

<table>
  <tr>
    <th>Name en</th>
    <th>Name no</th>
    <th>Festival</th>
    <th>Email</th>
    <th>Tag</th>
    <th>Description en</th>
    <th>Description no</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sections.each do |section| %>
  <tr>
    <td><%= section.name_en %></td>
    <td><%= section.name_no %></td>
    <td><%= section.festival_id %></td>
    <td><%= section.email %></td>
    <td><%= section.tag %></td>
    <td><%= section.description_en %></td>
    <td><%= section.description_no %></td>
    <td><%= link_to 'Show', section %></td>
    <td><%= link_to 'Edit', edit_section_path(section) %></td>
    <td><%= link_to 'Destroy', section, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New section</h1>

<%= render 'form' %>

<%= link_to 'Back', festival_sections_path %>

app/views/sections/show.html.erb
<div id="toolbar">
  <%= link_to("Edit section", edit_festival_section_path(@section.festival,@section), :class => :edit) %>
  <%= link_to("New group", new_section_group_path(@section), :class => :add) %>
</div>
<p id="notice"><%= notice %></p>
<div id="items">
  <% if @section.groups.any? %>
    <%= render :partial => 'groups/list', :locals => {:groups => @section.groups} %>
  <% else %>
    Empty section
  <% end %>
</div>