config/routes.rb
IsfitCore::Application.routes.draw do

 # match 'user/edit' => 'users#edit', :as => :edit_current_user

 # match 'signup' => 'users#new', :as => :signup

  resources :users do
    member do
      post 'generate_password'
    end
  end

  resources :roles
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resources :sessions
 # resources :organization do
 #   resources :festivals do
 #     resources :sections do
 #       resources :groups do
 #         resources :positions
 #       end
 #     end
 #     resources :groups do
 #       resources :positions
 #     end
 #   end
 #   resources :groups do
 #     resources :positions
 #   end
 # end

  resources :organization do
    resources :festivals
    resources :groups
  end
  resources :festivals do
    resources :sections
    resources :groups
  end
  resources :sections do
    resources :groups
  end
  resources :groups do
    resources :positions
  end
  resources :positions do
    resources :people
  end
  resources :people
  resources :isfit
  #match ':controller/:action' => '#index'
  root :to => "organization#show"
end

app/models/organization.rb
class Organization
  def self.festivals
    Festival.all(:order => 'year desc')
  end

  def self.groups
    Group.organization_groups(:order => :name)
  end
end

app/controllers/organization_controller.rb
class OrganizationController < ApplicationController
  def show
    set_where_am_i(nil)
  end
end

app/views/organization/people.html.erb
<div id="toolbar">
	<%=link_to("New person", new_person_path) %>
</div>
<% if Organization.people.any? %>
	<%=render :partial => 'people/list', :locals => {:people => Organization.people} %>
<%else%>
        Empty organization
<%end%>

app/views/organization/show.html.erb
<div id="toolbar">
  <%= link_to("New festival", new_organization_festival_path(:organization_id => 1), :class => :add) %>
  <%= link_to("New group", new_organization_group_path(:organization_id => 1), :class => :add) %>
  <%= link_to("Roles", roles_path, :class => :group) %>
</div>
<div id="items">
  <% if Organization.groups.any? || Organization.festivals.any? %>
    <%#= render :partial => 'groups/list', :locals => {:groups => Organization.groups} %>
    <%= render :partial => 'festivals/list', :locals => {:festivals => Organization.festivals} %>
  <% else %>
    Empty festival
  <% end %>
</div>  