config/routes.rb
IsfitCore::Application.routes.draw do

 # match 'user/edit' => 'users#edit', :as => :edit_current_user

 # match 'signup' => 'users#new', :as => :signup

  resources :users do
    member do
      post 'generate_password'
    end
  end

  resources :roles
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resources :sessions
 # resources :organization do
 #   resources :festivals do
 #     resources :sections do
 #       resources :groups do
 #         resources :positions
 #       end
 #     end
 #     resources :groups do
 #       resources :positions
 #     end
 #   end
 #   resources :groups do
 #     resources :positions
 #   end
 # end

  resources :organization do
    resources :festivals
    resources :groups
  end
  resources :festivals do
    resources :sections
    resources :groups
  end
  resources :sections do
    resources :groups
  end
  resources :groups do
    resources :positions
  end
  resources :positions do
    resources :people
  end
  resources :people
  resources :isfit
  #match ':controller/:action' => '#index'
  root :to => "organization#show"
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users_roles
  has_many :users_role_abstraction
  has_many :users, :through => :users_roles, :source => :user
  has_many :users_abstraction, :through => :users_role_abstraction, :source => :user

  has_and_belongs_to_many :sections
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :festivals

  attr_accessible :name, :user_tokens, :section_tokens, :group_tokens, :festival_tokens
  attr_reader :user_tokens, :section_tokens, :group_tokens, :festival_tokens

  def user_tokens=(ids)
    self.user_ids = ids.split(",")
  end
  def section_tokens=(ids)
    self.section_ids = ids.split(",")
  end
  def group_tokens=(ids)
    self.group_ids = ids.split(",")
  end
  def festival_tokens=(ids)
    self.festival_ids = ids.split(",")
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.xml
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.xml
  def show
    @role = Role.find(params[:id])
    @users = @role.users_abstraction
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.xml
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
    @users = @role.users_abstraction
  end

  # POST /roles
  # POST /roles.xml
  def create
    @role = Role.new(:name=>params[:role][:name]) 

    respond_to do |format|
      if @role.save and @role.update_attributes(params[:role])
        update_roles
        @role.save
        format.html { redirect_to(@role, :notice => 'Role was successfully created.') }
        format.xml  { render :xml => @role, :status => :created, :location => @role }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.xml
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        #Update all roles
        update_roles    
        @role.save
        format.html { redirect_to(@role, :notice => 'Role was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.xml
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to(roles_url) }
      format.xml  { head :ok }
    end
  end

private
  def update_roles
    @role.users_abstraction = []
    @role.festivals.each do |f|
      f.sections.each do |s|
        s.groups.each do |g|
          g.positions.each do |po|
            po.users.each do |u|
              unless u.nil?
                @role.users_abstraction << u
              end
            end
          end
        end
      end
    end
    @role.sections.each do |s|
      s.groups.each do |g|
        g.positions.each do |po|
          po.users.each do |u|
            unless u.nil?
              @role.users_abstraction << u
            end
          end
        end
      end
    end
    @role.groups.each do |g|
      g.positions.each do |po|
        po.users.each do |u|
          unless u.nil?
            @role.users_abstraction << u
          end
        end
      end
    end
    @role.users.each do |u|
      @role.users_abstraction << u
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :user %>
	 <%= f.text_field :user_tokens, "data-pre" => @role.users.map(&:id_name).to_json %>
    <%= f.label :group %>
	 <%= f.text_field :group_tokens, "data-pre" => @role.groups.map(&:id_name).to_json %>
    <%= f.label :section %>
    <%= f.text_field :section_tokens, "data-pre" => @role.sections.map(&:id_name).to_json %>
    <%= f.label :festival %>
    <%= f.text_field :festival_tokens, "data-pre" => @role.festivals.map(&:id_name).to_json %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>
<br /> <br />
<h2>Users with the role</h2>
<ul>
  <% @users.each do |u| %>
    <li><%= link_to(u.name, user_path(u)) %></li>
  <% end %>
</ul>

app/views/roles/index.html.erb
<div id="toolbar">
  <%= link_to("New role", new_role_path, :class => :add) %>
</div>
<div id="items">
<table>
<% @roles.each do |role| %>
  <tr>
    <td><%= link_to role.name, edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
</div>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p>
  <b>Name:</b>
  <%= @role.name %>
</p>
<p>
  <b>Users:</b>
<ul>
  <% @users.each do |u| %>
    <li><%= link_to(u.name, user_path(u)) %></li>
  <% end %>
</ul>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>